# Generated by Django 4.2.7 on 2023-11-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Type',
            field=models.CharField(default='Default Type', max_length=100),
        ),
    ]
