# Generated by Django 4.2.7 on 2023-11-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnb', '0002_property_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='Type',
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='property',
            name='numBathrooms',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='property',
            name='numBedrooms',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='property',
            name='secondaryImage',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='numGuests',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo')], default='house', max_length=100),
        ),
    ]
